// Generated by Wrangler on Sat Aug 17 2024 23:38:35 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	RIKI_INTERNAL_API_KEY: string;
	ASTRO_STUDIO_APP_TOKEN: string;
}
